language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: true

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - pip install -q numpy cython
  - python setup.py develop

before_script:
  - python -V

script:
  - python setup.py install

notifications:
  email: false
